AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  tofino-sam

  Sam-based version of tofino

Resources:
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: The security group for tofino Lmabda functions
      VpcId: 'vpc-04c5058d5d30e2414' # TODO: Migrate over from tofino CFN infrastructure
      SecurityGroupEgress:
        # TODO: Restrict the outbound traffic
        - CidrIp: '0.0.0.0/0'
          FromPort: -1
          ToPort: -1
          IpProtocol: '-1'

  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
  IndeedJobStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/indeed_job.asl.json
      DefinitionSubstitutions:
        IndeedSearcherFunctionArn: !GetAtt IndeedSearcherFunction.Arn
        IndeedDownloaderFunctionArn: !GetAtt IndeedDownloaderFunction.Arn
        IndeedJobParserFunctionArn: !GetAtt IndeedJobParserFunction.Arn
      Events:
        # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-statemachine-statemachineeventsource.html
        TriggeringSchedule:
          Type: Schedule
          Properties:
            Description: Schedule to run Indeed job state machine every 6 hour
            Enabled: False # This schedule is disabled by default to avoid incurring charges.
            Schedule: "rate(6 hours)"
            Input: "{\"url\":\"https://ca.indeed.com/jobs?q=data+analyst&sort=date&limit=50\"}"
      # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
      Policies: 
        - LambdaInvokePolicy:
            FunctionName: !Ref IndeedSearcherFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref IndeedDownloaderFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref IndeedJobParserFunction

  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  IndeedSearcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: functions.indeed_searcher.indeed_searcher.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Timeout: 30
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - 'subnet-0b64d55b9af846a53' # TODO: Migrate over from tofino CFN infrastructure
          - 'subnet-07f8bae144d20df3b' # TODO: Migrate over from tofino CFN infrastructure
      Policies:
        - VPCAccessPolicy: {}
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: '*' # TODO: Restrict to a certain resource
        - KMSDecryptPolicy:
            KeyId: '*' # TODO: Restrict to a certain resource
        - Statement:
          - Sid: InvokeLambdaFunctionPolicy
            Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource: '*' # TODO: Restrict to a certain resource

  IndeedDownloaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: functions.indeed_downloader.indeed_downloader.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Timeout: 30
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - 'subnet-0b64d55b9af846a53' # TODO: Migrate over from tofino CFN infrastructure
          - 'subnet-07f8bae144d20df3b' # TODO: Migrate over from tofino CFN infrastructure
      Environment:
        Variables:
          INDEED_JOB_POSTING_S3_BUCKET: !Ref IndeedJobPostingBucket
      Policies:
        - VPCAccessPolicy: {}
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: '*' # TODO: Restrict to a certain resource
        - KMSDecryptPolicy:
            KeyId: '*' # TODO: Restrict to a certain resource
        - Statement:
          - Sid: InvokeLambdaFunctionPolicy
            Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource: '*' # TODO: Restrict to a certain resource
        - S3WritePolicy:
            BucketName: !Ref IndeedJobPostingBucket

  IndeedJobParserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: functions.indeed_job_parser.indeed_job_parser.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64

  IndeedJobPostingBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

Outputs:
  # Find out more about other implicit resources you can reference within SAM
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources.html
  IndeedJobStateMachineArn:
    Description: "Indeed Job State machine ARN"
    Value: !Ref IndeedJobStateMachine
  IndeedJobStateMachineRoleArn:
    Description: "IAM Role created for Indeed Job State machine based on the specified SAM Policy Templates"
    Value: !GetAtt IndeedJobStateMachineRole.Arn
