# AWS
AWS_REGION = "us-west-2"

# TODO: change to Lambda environment varialbes
MYSQL_HOST = "tmwsfdnrcwbmp4.ca9x6xep5ulo.us-west-2.rds.amazonaws.com"
MYSQL_DB_NAME = "TOFINO_DB"
MYSQL_SECRET_NAME = "MySQL_application"

# Indeed
BUCKET_INDEED_JOB_POSTING_ENV_KEY = 'INDEED_JOB_POSTING_S3_BUCKET'

DYNAMODB_TABLE_CRAWLER_PROXY_ENV_KEY = 'CRAWLER_PROXY_TABLE'
DYNAMODB_TABLE_JOB_POSTING_ENV_KEY = 'JOB_POSTING_TABLE'
